it ('fb-signup', ()=>{
    cy.visit('https://www.facebook.com/')
    cy.get(':nth-child(2) > ._sv4').click()
    cy.get('[data-testid="open-registration-form-button"]').click()
    cy.wait(2000)
    cy.get('input[name="firstname"]').type('Adeem')
    cy.get('input[name="lastname"]').type('Mehdi')
    cy.get('input[name="reg_email__"]').type('goharabbas0308@gmail.com')
    cy.get('input[name="reg_email_confirmation__"]').type('goharabbas0308@gmail.com')
    cy.get('input[name="reg_passwd__"]').type('gohar123')
    cy.get('#day').select('22')
    cy.get('#month').select('Jan')
    cy.get('#year').select('1997')
    cy.get('input[name="sex"]').check('2')
    cy.get('button[name="websubmit"]').click()
})